spring.application.name=CustomerApp
spring.jpa.hibernate.ddl-auto= update
spring.datasource.url=jdbc:sqlserver://web-app-db-server-test.database.windows.net:1433;database=customer-db;user=web-app-db-admin@web-app-db-server-test;password=test123@;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;